apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spvedtak
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://spvedtak.dev.nav.no/"
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: internal/isAlive
  readiness:
    path: internal/isReady
  env:
    - name: SYFOAPI_ROOT
      value: "https://syfoapi-q.nav.no"
    - name: SYFOREST_ROOT
      value: "https://tjenester-q1.nav.no/syforest"
    - name: LOGINSERVICE_URL
      value: "https://loginservice-q.nav.no/login"
    - name: UNLEASH_URL
      value: "https://tjenester-q1.nav.no/syfounleash"
    - name: AMPLITUDE_ENABLED
      value: "false"
    - name: MOCK_BACKEND
      value: "true"
    - name: DECORATOR_URL
      value: "https://www-q1.nav.no/dekoratoren"
    - name: ENVIRONMENT
      value: "q1"
    - name: SYKEFRAVAER_URL
      value: "https://sykefravaer.labs.nais.io"
    - name: OPPLAERING
      value: "true"
