apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-frontend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://www.nav.no/syk/sykepenger"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: internal/isAlive
  readiness:
    path: internal/isReady
  env:
    - name: SYFOAPI_ROOT
      value: "https://syfoapi.nav.no"
    - name: SYKMELDINGER_BACKEND_PROXY_ROOT
      value: "https://sykmeldinger-backend-proxy.nav.no"
    - name: SPINNSYN_ROOT
      value: "https://spinnsyn-backend-proxy.nav.no"
    - name: FLEXINNTEKTSMELDING_ROOT
      value: "https://flex-inntektsmelding-proxy.nav.no"
    - name: LOGINSERVICE_URL
      value: "https://loginservice.nav.no/login"
    - name: MOCK_BACKEND
      value: "false"
    - name: DECORATOR_URL
      value: "https://www.nav.no/dekoratoren"
    - name: ENVIRONMENT
      value: "prod"
    - name: SYKEFRAVAER_URL
      value: "https://tjenester.nav.no/sykefravaer"
    - name: OPPLAERING
      value: "false"
    - name: LOGINSERVICE_REDIRECT_URL
      value: "https://www.nav.no/syk/sykepenger"
    - name: FRONTENDLOGGER_ROOT
      value: "https://tjenester.nav.no"
