apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-frontend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://sykepenger.dev.nav.no/"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: internal/isAlive
  readiness:
    path: internal/isReady
  env:
    - name: SYFOAPI_ROOT
      value: "https://syfoapi.dev.nav.no"
    - name: SYKMELDINGER_BACKEND_PROXY_ROOT
      value: "https://sykmeldinger-backend-proxy.dev.nav.no"
    - name: SPINNSYN_ROOT
      value: "https://spinnsyn-backend-proxy.dev.nav.no"
    - name: FLEXINNTEKTSMELDING_ROOT
      value: "https://flexinntektsmelding-proxy.dev.nav.no"
    - name: LOGINSERVICE_URL
      value: "https://loginservice.dev.nav.no/login"
    - name: MOCK_BACKEND
      value: "false"
    - name: DECORATOR_URL
      value: "https://dekoratoren.dev.nav.no"
    - name: ENVIRONMENT
      value: "q1"
    - name: SYKEFRAVAER_URL
      value: "https://sykefravaer.er.ikke.tilgjengelig.fra.naisdevice.ennå.no"
    - name: OPPLAERING
      value: "false"
    - name: LOGINSERVICE_REDIRECT_URL
      value: "https://sykepenger.dev.nav.no"
    - name: FRONTENDLOGGER_ROOT
      value: "https://tjenester-q1.nav.no"
