apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-frontend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - {{ingress}}
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  resources:
    limits:
      cpu: 1000m
      memory: 400Mi
    requests:
      cpu: 100m
      memory: 200Mi
  liveness:
    path: syk/sykepenger/api/internal/isAlive
  readiness:
    path: syk/sykepenger/api/internal/isReady
  startup:
    path: syk/sykepenger/api/internal/isAlive
    initialDelay: 30
  accessPolicy:
    outbound:
      rules:
        - application: spinnsyn-backend
        - application: flex-hotjar-emotions
        - application: sokos-kontoregister-person
          namespace: okonomi
      external:
        - host: www.nav.no                      # for prod
        - host: dekoratoren.ekstern.dev.nav.no  # for dev
  tokenx:
    enabled: true
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}


